CREATE TYPE user_state AS ENUM (
  'USER_STATE_ACTIVE',
  'USER_STATE_SUSPENDED',
  'USER_STATE_LOCKED'
);

CREATE TABLE users (
  id UUID PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  state user_state NOT NULL DEFAULT 'USER_STATE_ACTIVE',
  create_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON users(email);